### ISSUE TITLE
[Request] Check what tweaks applied and export/import config

### ISSUE THREAD

**Issue by Drovosek01** [ivandfx/DFXWinTweaks#3]
Thanks for the cool CLI for configuring Windows, but in my opinion it lacks several important functions:

1. Check which tweaks have already been applied in the system (for example, dark mode is already enabled)
2. Export and import settings for applying tweaks. If I need to apply the same tweak settings to several operating systems (computers) using your utility, I will have to go through all the steps of enabling tweaks again in each operating system. It's inconvenient. (Maybe I didn't notice, but I didn't find the export and import function of the current settings)

**Comment by ivandfx** [comment]
Thank you for your request and for sharing you opinion! :D

**1.** Checking what tweaks you have applied could be a bit complex to implement in VBS CLI, but I could try to add it in a future release.
**2.** I'm already on the works to create a new menu with some tweaking presets, maybe that will work for you, and if you want, you can tell me what tweaks you usually apply and I could create a preset with those tweaks in mind.

If this answer is not what you wanted, you can tell me.

**Comment by Drovosek01** [comment]
> **2.** I'm already on the works to create a new menu with some tweaking presets, maybe that will work for you, and if you want, you can tell me what tweaks you usually apply on the different OS' and I could create a preset with those tweaks in mind.
> 
> If this answer is not what you wanted, you can tell me.

Thank you for fast answer.

I have to reinstall Windows several times a year and after each reinstall I configure it and all installed applications anew.

I decided to find a way to fix all the settings that I apply, so that after reinstalling I could apply all these settings immediately in automatic mode, and not manually mark the checkboxes in the parameters of each application.

Now I have made a file with [tweaks](https://github.com/Drovosek01/settings/blob/master/OSes/Windows/tweaks.reg) for myself, but not all the settings of Windows and its standard applications can be changed by tweaks or items in the registry, and I am looking for an application that can do this, and can also export and sort the selected settings.

I found a list of utilities for changing settings on page on [MajorGeeks](https://www.majorgeeks.com/mg/sortdate/windows_7_8.html) and there I also found a link to your utility.

I have performed small tests for more than 15 utilities from that list and so far only in [Ultimate Windows Tweaker](https://www.thewindowsclub.com/ultimate-windows-tweaker-4-windows-10) I have found the function of exporting and importing the applied settings

In utility [ChrisTitusTech/winutil](https://github.com/ChrisTitusTech/winutil) I found an analysis function... by clicking on the "Get installed" button, the utility checks the tweaks or programs that are already installed. It's convenient

I hope you will be able to make a cool utility, but I will continue my search for now.

**Comment by ivandfx** [comment]
Thanks for your answer.

I always recommend someone to use what suits them best if it meets their needs, and all the utilities you mentioned are really amazing.

I am a newbie developer and I try my best to improve DFX WinTweaks, with time it will get better and have more features, and with user feedback I can get more ideas on what to add to the script in the future.

It is good to know that there are other more complete utilities that people can use.

See ya!
