### ISSUE TITLE
Windows installed to another location, not at C:\Windows

### ISSUE THREAD

**Issue by HKLM** [ivandfx/DFXWinTweaks#4]
script fails when Windows is installed to a different location than the default C:\Windows

I would suggest to change the hard coded 
```
objShell.Run "C:\WINDOWS\system32\shutdown.exe -r -t 0"
```
and use the environment variable "%WINDIR% that will allways point to correct windows folder (ie if windows is installed on the D drive "D:\Windows")
```
objShell.Run "%WINDIR%\system32\shutdown.exe -r -t 0"
```

**Comment by ivandfx** [comment]
Wow, I didn't think about this before.
I just fixed this issue with [3.4.2/3.3.2 ESR](https://github.com/ivandfx/DFXWinTweaks/releases/tag/v3.4.2%2Fv3.3.2ESR), thank you for pointing this out!

If you have any other issue, feel free to tell! 😉
